backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
      - file: "about.html"
        label: "About Us Page"
        name: "about"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
